# 009ndarray的属性

## shape，ndim，size，dtype

In [88]:
#指定数据类型
import numpy as np
list1=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(list1,dtype=np.float64)
print(arr.ndim)
print(arr.shape)
print(arr)


1
(10,)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [93]:
# 指定形状，包括全0型，全一型，未初始化，固定值
arr=np.zeros((2,1),dtype=np.int64)
print(arr)

[[0]
 [0]]


#学习了zeros ones empty full zeros_like、ones_like、empty_like、full_like(仅复制形状，不复制矩阵内数值）的使用

In [6]:
#full:（(行，列），填充的数字）
arr=np.full((3,4),2)
print(arr)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [9]:
arr1=np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# 010

In [11]:
#等差数列 np.arange的使用:(start,end,step)
#比如想要创建一个1-10的等差数列，公差是1
arr=np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [17]:
#等间隔数列 np.linspace的使用(start,end,个数)
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [24]:
#对数间隔数列：(第一个结果，第二个结果，生成个数，base=以谁为底)
arr=np.logspace(0,9,2,base=2)
print(arr)
arr1=np.linspace(0,55,5)
print(arr1)
arr2=np.logspace(0,55,5,base=2)
print(arr2)

[  1. 512.]
[ 0.   13.75 27.5  41.25 55.  ]
[1.00000000e+00 1.37772469e+04 1.89812531e+08 2.61509410e+12
 3.60287970e+16]


# 011：特殊矩阵的创建：五个命令

## 1、单位阵eye(行，列，数据类型）

In [30]:
arr=np.eye(3,4,dtype=np.int64)  
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


## 2、对角阵diag[（a,b,c,d)]:展现为对角线元素//记得加中括号！！！！！

In [35]:
arr=np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## 3、随机数组的生成


### 3.1生成0-1之间的随机浮点数（均匀分布）np.random.rand(行，列)

In [36]:
arr=np.random.rand(2,3)
print(arr)

[[0.34406836 0.45060254 0.37815139]
 [0.70733299 0.93440515 0.87334516]]


### 3.2生成指定范围区间的随机浮点数（均匀分布）np.random.uniform(左范围，右范围，（行，列））

In [39]:
arr=np.random.uniform(3,5,(2,3))
print(arr)

[[4.00948532 3.11355487 4.5249278 ]
 [3.96511617 4.78887732 4.7849233 ]]


### 3.3生成指定范围的随机整数np.random.randint(左范围，右范围(行，列))

In [40]:
arr=np.random.randint(520,1314,(3,4))
print(arr)

[[ 762  688  992 1060]
 [ 681 1123 1102  764]
 [ 699 1057  784  770]]


### 3.4生成随机数列（正态分布）np.random,randn(行，列)

In [60]:
arr=np.random.randn(3,4)
print(arr)

[[ 0.97325814 -0.61270501  1.14621179  0.54218808]
 [-0.59575446  0.16317204 -1.08561693  0.6214763 ]
 [-0.72090969  1.01876157  0.42538661  1.62232687]]


### 3.5设置随机种子np.random.seed(),目的是在与其他用户进行数据交替的时候能够生成跟我一个种子下生成的矩阵，比如我们都把种子设置成20，那我们两个生成的矩阵是相同的

In [82]:
np.random.seed(40)
arr=np.random.randint(3,100,(3,4))
print(arr)

[[47 50 67 70]
 [70 12 86 24]
 [39 90 73 91]]


# 013数据索引与切片，就是取数据

## 一维数组的索引切片

### 先复习获取一维数组

In [97]:
arr=np.random.randint(0,100,20)
print(arr)

[65 39 87 46 88 81 37 25 77 72  9 20 80 69 79 47 64 82 99 88]


### 一维数组索引方法

In [98]:
print(arr[:])#意思是获取全部数据

[65 39 87 46 88 81 37 25 77 72  9 20 80 69 79 47 64 82 99 88]


In [99]:
print(arr[2:5])#意思是索引第二位置到第四位置的数，左包右不包

[87 46 88]


In [100]:
print(arr[arr>10])#布尔类型，取大于10的数字

[65 39 87 46 88 81 37 25 77 72 20 80 69 79 47 64 82 99 88]


In [102]:
print(arr[(arr>10) & (arr<70)])#用逻辑关系的时候记得用括号括起来，不能用and

[65 39 46 37 25 20 69 47 64]


### slice的运用,slice(start,end,step)

In [103]:
print(arr[slice(2,15,3)])

[87 81 77 20 79]


## 二维数组的索引与切片

### 先定义一个二维矩阵

In [112]:
arr=np.random.randint(0,100,(6,9))
print(arr)

[[42 84 75 68  6 68 47  3 76]
 [52 78 15 20 99 58 23 79 13]
 [85 48 49 69 41 35 64 95 69]
 [94  0 50 36 34 48 93  3 98]
 [42 77 21 73  0 10 43 58 23]
 [59  2 98 62 35 94 67 82 46]]


### 二维索引

In [123]:
print(arr[1,2])
print(arr[3,5:9])
print(arr[4:6,3])
print(arr[(arr>80) & (arr<90)])
print(arr[2][arr[2]>50])#某一行的布尔索引
print(arr[:,3][arr[:,3]>50])#某一列进行布尔索引

15
[48 93  3 98]
[73 62]
[84 85 82]
[85 69 64 95 69]
[68 69 73 62]


# 014 ndarray的运算

## 算术运算

In [125]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
