# 基本数学函数

## 计算平方根sqrt

In [2]:
import numpy as np
print(np.sqrt(2))

1.4142135623730951


## 计算指数exp e的x次方

In [4]:
print(np.exp(0))

1.0


## 计算自然对数log,默认以e为底

In [5]:
print(np.log(np.exp(0)))

0.0


## 计算三角函数

## 计算绝对值abs

## 计算a的b次幂值power

In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.power(arr,2))

[ 1  4  9 16 25 36 49 64 81]


## 四舍五入round

In [7]:
arr=np.array([1.2,3.4,5.6,7.8,8.9,9.0])
print(np.round(arr))

[1. 3. 6. 8. 9. 9.]


## 向上取整ceil，向下取整floor

In [8]:
arr=np.array([1.2,3.4,5.6,7.8,8.9,9.0])
print(np.ceil(arr))
print(np.floor(arr))

[2. 4. 6. 8. 9. 9.]
[1. 3. 5. 7. 8. 9.]


## 检测缺失值nan（导入Excel的时候有用）

In [9]:
np.isnan([1,2,3,4,5,6,np.nan,8,9])

array([False, False, False, False, False, False,  True, False, False])