#ndarray学习

##1.ndarray特性

In [3]:
import numpy as np

In [27]:
arr=np.array(5)
print(arr)
print("维度是：",arr.ndim)
print("形状是：",arr.shape)

5
维度是： 0
形状是： ()


In [12]:
arr=np.array([1,2,3,4])
print(arr)
print("维度是：",arr.ndim)

[1 2 3 4]
维度是： 1


In [18]:
arr=np.array([[1,2,3],[2,3,3]])
print(arr)
print("维度是：",arr.ndim)

[[1 2 3]
 [2 3 3]]
维度是： 2


#同质性

In [22]:
arr=np.array([1,"hello"])#强制转换为相同的性质
print(arr)

['1' 'hello']


In [24]:
arr=np.array([1,1.312])
print(arr)

[1.    1.312]
