# 题目1：温度数据分析
某城市一周最高温度为[28,30,29,31,32,30,29].
计算平均气温、最高气温和最低气温。
找出气温超过三十度的天数

In [12]:
import numpy as np
arr=np.array([28,30,29,31,32,30,29])
print("%.2f"%np.average(arr))#紫色是保留两位小数的意思
print(np.max(arr))
print(np.min(arr))
print(arr[arr>30])#bool索引的方法得记住

29.86
32
28
2


# 第二题学生成绩统计
五个同学的数学成绩是[85,90,78,92,88]
计算平均分，中位数和标准差
将成绩转换为10分制

In [27]:
arr=np.array([85,90,78,92,88])
print("平均分是：",np.mean(arr))
print("中位数是：",np.median(arr))
print("标准差是：","%.3f"%np.std(arr))
print("转换为十分制为：",(arr/10))

平均分是： 86.6
中位数是： 88.0
标准差是： 4.883
转换为十分制为： [8.5 9.  7.8 9.2 8.8]


# 第三题：矩阵运算
计算a=[(1,2),(3,4)]和矩阵b=[(5,6),(7,8)]的相加相乘和点积运算


In [35]:
clq=np.array(([1,2],[3,4]))#创建矩阵有说法，array后面必须带括号，矩阵得用中括号括起来
pll=np.array([(5,6),(7,8)])#三种方法都可以
print(clq+pll)
print(clq*pll)
print(clq/pll)
print(clq@pll)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


# 第四题：生成一个3×4的随机整数数组，范围（0,10）
计算每列的最大值和最小值
将数组中的所有奇数替换为-1

In [45]:
arr=np.random.randint(0,10,(3,4))
print(arr)
print("第一列的最大值为：",np.max(arr,axis=0))#axis=0是列，=1是行
print("第一列的最小值为：",np.min(arr,axis=0))#axis=0是列，=1是行
print(np.where(arr%2==1,-1,arr))

[[4 5 8 8]
 [5 7 9 0]
 [7 5 0 2]]
第一列的最大值为： [7 7 9 8]
第一列的最小值为： [4 5 0 0]
[[ 4 -1  8  8]
 [-1 -1 -1  0]
 [-1 -1  0  2]]
